// ──────────────────────────────────────────────
// CreditBridge — PDF Format Detector
// ──────────────────────────────────────────────
//
// Identifies which credit-monitoring provider generated a PDF report
// by pattern-matching text content for provider-specific signatures.
// Each provider's PDF reports contain unique header/footer branding,
// watermarks, URLs, phone numbers, or proprietary terminology that
// this module uses to fingerprint the source.
// ──────────────────────────────────────────────

/**
 * Result returned by the format detector.
 */
export interface FormatDetectionResult {
  /** Normalized provider identifier (matches provider_capabilities.provider_name) */
  provider: string;
  /** Confidence 0.0-1.0 in the detection */
  confidence: number;
  /** Human-readable detail about which pattern(s) matched */
  matchedPattern: string;
}

/**
 * Internal rule: a regex or string pattern to match, plus metadata.
 */
interface DetectionRule {
  provider: string;
  /** Primary pattern — high-confidence match */
  primary: RegExp[];
  /** Secondary patterns — boost confidence if also found */
  secondary: RegExp[];
  /** Excluder patterns — if these match, reduce or negate confidence */
  excluders: RegExp[];
}

// ── Detection Rules ────────────────────────────
//
// Each provider rule is built from observing actual report PDFs.
// Primary patterns are unique to that provider and rarely appear in
// other providers' reports. Secondary patterns strengthen the match.
// Excluders help disambiguate (e.g., a provider that resells another's
// report may contain the upstream brand).

const DETECTION_RULES: DetectionRule[] = [
  // ── SmartCredit ──────────────────────────────
  // SmartCredit reports are generated by ConsumerDirect, Inc. and
  // typically contain "SmartCredit" branding in headers, along with
  // unique URLs, phone numbers, and member ID formats.
  {
    provider: "SmartCredit",
    primary: [
      /SmartCredit\s*(?:Premier|Report|Score)?/i,
      /SmartCredit\.com/i,
      /ConsumerDirect(?:,?\s*Inc\.?)?/i,
      /888-\d{3}-\d{4}.*SmartCredit/i,
    ],
    secondary: [
      /smartcredit\.(?:com|net)/i,
      /SCORE\s*SUMMARY\s*-\s*SmartCredit/i,
      /Member\s*ID[:\s]*\d{6,10}/i,
    ],
    excluders: [],
  },

  // ── MyScoreIQ ────────────────────────────────
  // MyScoreIQ reports show "MyScoreIQ" or "My Score IQ" branding,
  // often with "myScoreIQ.com" URL and specific report IDs.
  {
    provider: "MyScoreIQ",
    primary: [
      /MyScoreIQ/i,
      /My\s*Score\s*IQ/i,
      /myScoreIQ\.com/i,
      /Score\s*IQ\s*(?:Report|Monitoring)/i,
    ],
    secondary: [
      /myscoreiq/i,
      /Identity\s*IQ\s*.*MyScore/i, // cross-branded documents
    ],
    excluders: [
      // If IdentityIQ is prominent, it's likely an IdentityIQ report
      // with a MyScoreIQ cross-promotion, not a MyScoreIQ report itself.
      /IdentityIQ\s*(?:Premier|Platinum|Ultra)/i,
    ],
  },

  // ── IdentityIQ ───────────────────────────────
  // IdentityIQ reports are produced by IDIQ (Identity Intelligence).
  // These typically have "IdentityIQ" in headers, unique member IDs,
  // and specific phone numbers for support.
  {
    provider: "IdentityIQ",
    primary: [
      /IdentityIQ/i,
      /IDIQ/i,
      /Identity\s*IQ\s*(?:Premier|Platinum|Secure|Ultra)/i,
      /identityiq\.com/i,
    ],
    secondary: [
      /Bitdefender.*Identity/i, // often bundled
      /IDIQ.*Member/i,
      /877-\d{3}-\d{4}.*Identity/i,
    ],
    excluders: [],
  },

  // ── Credit Hero Score ────────────────────────
  // Credit Hero Score reports are more basic — often a single-page
  // score summary. Look for "Credit Hero" branding and affiliated URLs.
  {
    provider: "Credit Hero Score",
    primary: [
      /Credit\s*Hero\s*Score/i,
      /CreditHero/i,
      /creditscorehero\.com/i,
      /Hero\s*Score\s*Report/i,
    ],
    secondary: [
      /Credit\s*Hero\s*(?:Monitoring|Dashboard)/i,
    ],
    excluders: [],
  },
];

/**
 * Confidence thresholds for detection quality.
 */
const CONFIDENCE = {
  /** Single primary match gives high confidence */
  PRIMARY_MATCH: 0.85,
  /** Secondary match adds a small boost per match */
  SECONDARY_BOOST: 0.05,
  /** Max boost from secondary matches */
  MAX_SECONDARY_BOOST: 0.10,
  /** Excluder match penalty per match */
  EXCLUDER_PENALTY: 0.30,
  /** Floor after penalties */
  MIN_CONFIDENCE: 0.0,
  /** Cap at 1.0 */
  MAX_CONFIDENCE: 1.0,
};

/**
 * Detect which provider generated this PDF report from its text content.
 *
 * @param pdfText - The full text extracted from the PDF via pdf-parse.
 * @returns Detection result with provider name and confidence.
 *
 * Example:
 *   detectProviderFormat("...SmartCredit Premier Report...")
 *   // => { provider: "SmartCredit", confidence: 0.85, matchedPattern: "SmartCredit" }
 */
export function detectProviderFormat(pdfText: string): FormatDetectionResult {
  if (!pdfText || pdfText.trim().length === 0) {
    return { provider: "unknown", confidence: 0, matchedPattern: "empty_text" };
  }

  let best: FormatDetectionResult = {
    provider: "unknown",
    confidence: 0,
    matchedPattern: "no_match",
  };

  for (const rule of DETECTION_RULES) {
    let confidence = 0;
    const matched: string[] = [];

    // Check primary patterns — at least one must match
    for (const pattern of rule.primary) {
      if (pattern.test(pdfText)) {
        // Extract the matched text for reporting
        const m = pdfText.match(pattern);
        if (m) matched.push(m[0]);
        confidence = CONFIDENCE.PRIMARY_MATCH;
        break; // one primary match is enough
      }
    }

    if (confidence === 0) continue; // no primary match, skip this provider

    // Check secondary patterns for confidence boost
    let secondaryBoost = 0;
    for (const pattern of rule.secondary) {
      if (pattern.test(pdfText)) {
        secondaryBoost += CONFIDENCE.SECONDARY_BOOST;
        if (secondaryBoost >= CONFIDENCE.MAX_SECONDARY_BOOST) break;
      }
    }
    confidence = Math.min(confidence + secondaryBoost, CONFIDENCE.MAX_CONFIDENCE);

    // Apply excluder penalties
    for (const pattern of rule.excluders) {
      if (pattern.test(pdfText)) {
        confidence = Math.max(
          CONFIDENCE.MIN_CONFIDENCE,
          confidence - CONFIDENCE.EXCLUDER_PENALTY
        );
      }
    }

    if (confidence > best.confidence) {
      best = {
        provider: rule.provider,
        confidence: Math.round(confidence * 100) / 100,
        matchedPattern: matched.join(" | "),
      };
    }
  }

  return best;
}
